// Shared product data for consistency across the application
export const products = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description:
      "Premium noise-cancelling headphones with 30hr battery life and deep bass",
    price: 129,
    originalPrice: 199,
    rating: 4.8,
    reviewCount: 245,
    image:
      "https://images.pexels.com/photos/205926/pexels-photo-205926.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "electronics",
    featured: true,
    features: [
      "Active noise cancellation",
      "30-hour battery life",
      "Bluetooth 5.0 connectivity",
      "Built-in microphone",
      "Comfortable over-ear design",
      "Quick charge technology",
    ],
    details: {
      "Battery Life": "30 hours",
      Connectivity: "Bluetooth 5.0",
      "Noise Cancellation": "Active",
      Weight: "250g",
      Warranty: "1 year",
      "Charging Time": "2 hours",
    },
  },
  {
    id: "2",
    name: "Smart Fitness Tracker",
    description:
      "Track steps, heart rate, sleep quality and receive smartphone notifications",
    price: 79,
    originalPrice: 129,
    rating: 4.6,
    reviewCount: 189,
    image:
      "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "electronics",
    featured: true,
    features: [
      "Heart rate monitoring",
      "Sleep tracking",
      "Step counter",
      "Smartphone notifications",
      "Water resistant",
      "7-day battery life",
    ],
    details: {
      "Battery Life": "7 days",
      Connectivity: "Bluetooth",
      "Water Resistance": "IP67",
      Display: "Color touchscreen",
      Sensors: "Heart rate, accelerometer",
      Compatibility: "iOS & Android",
    },
  },
  {
    id: "3",
    name: "Portable Phone Charger",
    description:
      "10000mAh fast-charging power bank with dual USB ports for multiple devices",
    price: 39,
    originalPrice: 59,
    rating: 4.7,
    reviewCount: 321,
    image:
      "https://images.pexels.com/photos/2659939/pexels-photo-2659939.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "electronics",
    featured: false,
    features: [
      "10000mAh capacity",
      "Dual USB ports",
      "Fast charging support",
      "LED power indicator",
      "Compact and lightweight",
      "Universal compatibility",
    ],
    details: {
      Capacity: "10000mAh",
      Ports: "2x USB-A",
      "Input Port": "Micro USB",
      "Output Port": "USB-A",
      Weight: "220g",
      Dimensions: "150x75x15mm",
    },
  },
  {
    id: "4",
    name: "Designer Leather Wallet",
    description:
      "Genuine leather wallet with multiple card slots and RFID protection",
    price: 49,
    originalPrice: 79,
    rating: 4.5,
    reviewCount: 142,
    image:
      "https://images.pexels.com/photos/205740/pexels-photo-205740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "accessories",
    featured: true,
    features: [
      "Genuine leather material",
      "RFID protection",
      "Multiple card slots",
      "Cash compartment",
      "Coin pocket",
      "Premium stitching",
    ],
    details: {
      Material: "Genuine leather",
      "RFID Protection": "Yes",
      Slots: "8 card slots",
      Compartments: "2 cash, 1 coin",
      Dimensions: "190x95mm",
      Weight: "120g",
    },
  },
  {
    id: "5",
    name: "Stainless Steel Water Bottle",
    description:
      "Double-walled insulated bottle keeps drinks cold for 24hrs or hot for 12hrs",
    price: 29,
    originalPrice: 39,
    rating: 4.9,
    reviewCount: 278,
    image:
      "https://images.pexels.com/photos/2085433/pexels-photo-2085433.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "home",
    featured: false,
    features: [
      "Double-walled insulation",
      "Keeps cold for 24 hours",
      "Keeps hot for 12 hours",
      "Leak-proof design",
      "BPA-free materials",
      "Ergonomic grip",
    ],
    details: {
      Capacity: "500ml",
      Material: "Stainless steel",
      Insulation: "Double-walled",
      "Lid Type": "Screw-on",
      Dimensions: "220x70mm",
      Weight: "280g",
    },
  },
  {
    id: "6",
    name: "Wireless Charging Pad",
    description:
      "Fast wireless charging compatible with all Qi-enabled devices",
    price: 24,
    originalPrice: 39,
    rating: 4.4,
    reviewCount: 98,
    image:
      "https://images.pexels.com/photos/3781527/pexels-photo-3781527.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "electronics",
    featured: false,
    features: [
      "Qi wireless charging",
      "Fast charging support",
      "Compatible with all Qi devices",
      "LED indicator",
      "Non-slip surface",
      "Compact design",
    ],
    details: {
      Compatibility: "All Qi-enabled devices",
      "Charging Speed": "10W max",
      Input: "5V/2A",
      Output: "5W/10W",
      Dimensions: "100x100x10mm",
      Weight: "120g",
    },
  },
  {
    id: "7",
    name: "Smart Home Security Camera",
    description:
      "1080p HD indoor camera with night vision and mobile app control",
    price: 89,
    originalPrice: 129,
    rating: 4.7,
    reviewCount: 156,
    image:
      "https://images.pexels.com/photos/40215/gear-home-security-padlock-40215.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "electronics",
    featured: true,
    features: [
      "1080p HD video",
      "Night vision",
      "Mobile app control",
      "Motion detection",
      "Two-way audio",
      "Cloud storage support",
    ],
    details: {
      Resolution: "1080p HD",
      "Night Vision": "Yes",
      Connectivity: "Wi-Fi",
      "Field of View": "110°",
      Storage: "Cloud/SD card",
      Power: "5V/1A",
    },
  },
  {
    id: "8",
    name: "Ergonomic Office Chair",
    description:
      "Adjustable lumbar support chair for comfortable long work sessions",
    price: 299,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 87,
    image:
      "https://images.pexels.com/photos/164768/pexels-photo-164768.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "home",
    featured: false,
    features: [
      "Adjustable lumbar support",
      "Breathable mesh back",
      "360° swivel",
      "Height adjustable",
      "Armrests adjustable",
      "Tilt mechanism",
    ],
    details: {
      Material: "Mesh + Metal",
      "Weight Capacity": "150kg",
      Adjustments: "Height, tilt, armrests",
      Wheels: "5 casters",
      Dimensions: "60x60x110cm",
      Weight: "18kg",
    },
  },
  {
    id: "9",
    name: "Bluetooth Wireless Speaker",
    description: "360° surround sound with deep bass and 15hr playtime",
    price: 129,
    originalPrice: 179,
    rating: 4.6,
    reviewCount: 203,
    image:
      "https://images.pexels.com/photos/164660/pexels-photo-164660.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "electronics",
    featured: true,
    features: [
      "360° surround sound",
      "15-hour battery life",
      "Water resistant",
      "Bluetooth connectivity",
      "Deep bass technology",
      "Built-in microphone",
    ],
    details: {
      "Battery Life": "15 hours",
      Connectivity: "Bluetooth 5.0",
      "Water Resistance": "IPX7",
      Drivers: "2x 10W",
      Frequency: "50Hz-20kHz",
      Dimensions: "180x70mm",
    },
  },
  {
    id: "10",
    name: "Organic Cotton T-Shirt Bundle",
    description: "Pack of 3 premium organic cotton t-shirts in assorted colors",
    price: 59,
    originalPrice: 79,
    rating: 4.9,
    reviewCount: 167,
    image:
      "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "fashion",
    featured: false,
    features: [
      "100% organic cotton",
      "Set of 3 t-shirts",
      "Assorted colors",
      "Soft and comfortable",
      "Machine washable",
      "Eco-friendly materials",
    ],
    details: {
      Material: "100% organic cotton",
      Sizes: "S, M, L, XL",
      Colors: "Assorted",
      "Sleeve Type": "Short sleeve",
      Fit: "Regular fit",
      Care: "Machine washable",
    },
  },
  {
    id: "11",
    name: "Stainless Steel Cookware Set",
    description:
      "10-piece professional grade cookware set with non-stick coating",
    price: 199,
    originalPrice: 299,
    rating: 4.8,
    reviewCount: 92,
    image:
      "https://images.pexels.com/photos/160408/pexels-photo-160408.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "home",
    featured: true,
    features: [
      "10-piece set",
      "Non-stick coating",
      "Stainless steel construction",
      "Oven safe up to 260°C",
      "Dishwasher safe",
      "Ergonomic handles",
    ],
    details: {
      Pieces: "10-piece set",
      Material: "Stainless steel",
      Coating: "Non-stick",
      "Oven Safe": "Up to 260°C",
      Handles: "Ergonomic, stay-cool",
      "Lid Material": "Tempered glass",
    },
  },
  {
    id: "12",
    name: "UV Protection Sunglasses",
    description:
      "Polarized lenses with UV400 protection and lightweight frame design",
    price: 49,
    originalPrice: 79,
    rating: 4.7,
    reviewCount: 134,
    image:
      "https://images.pexels.com/photos/1080983/pexels-photo-1080983.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    category: "accessories",
    featured: false,
    features: [
      "UV400 protection",
      "Polarized lenses",
      "Lightweight frame",
      "Anti-scratch coating",
      "100% UV protection",
      "Comfortable nose bridge",
    ],
    details: {
      Lenses: "Polarized",
      "UV Protection": "UV400",
      Frame: "Lightweight plastic",
      "Lens Material": "Polycarbonate",
      Weight: "120g",
      "Frame Color": "Black",
    },
  },
];
